/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package package1;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author sarvottam
 */
public class Hiding extends javax.swing.JFrame {
    String name, str1, f, temp;
    /**
     * Creates new form Hiding
     */
    public Hiding(String str,String s) {
       name=str;
       str1=s;
      
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 220, 43);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 130, 220, 39);

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(340, 50, 260, 41);

        jPasswordField2.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField2.setOpaque(false);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(340, 120, 260, 39);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setText("Hide");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 300, 140, 40);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(153, 153, 153));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(60, 440, 537, 26);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 380, 180, 31);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter the name of encoded image");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(84, 204, 380, 30);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(530, 190, 230, 40);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(680, 423, 140, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/Pictures/background1920x1080.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -10, 880, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String s1=new String(jPasswordField1.getPassword());
            String s2=new String(jPasswordField2.getPassword());  
            boolean flag=false;
            /*if(name.endsWith(".png"))
                f="png";
            else if(name.endsWith(".gif")) 
                f="gif";
            else if(name.endsWith(".bmp")) 
                f="bmp";*/
            
            if(!(s1.contentEquals(s2)))
            {
             JOptionPane.showMessageDialog(this, "Password mismatch", "ERROR!!!!!!", JOptionPane.INFORMATION_MESSAGE);
             
             jPasswordField2.setText("");
            }
            else
            {
              try
        {
            if((new String(jPasswordField1.getPassword())).equals("") || (new String(jPasswordField2.getPassword())).equals("") || jTextField1.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please fill all entries correctly.", "ERROR!!!!!!", JOptionPane.ERROR_MESSAGE);
                flag=false;
            }
            String format=jTextField1.getText();
            Socket client;
     BufferedReader in;
     PrintWriter out;
          client=new Socket("localhost",2013);
            in=new BufferedReader(new InputStreamReader(client.getInputStream()));
            out=new PrintWriter(client.getOutputStream(),true);
            out.println("hide");
            out.println(format);
            out.println(s1);
            String str=in.readLine();
            if(str.equals("error"))
            {
                JOptionPane.showMessageDialog(this, "Filename already present. Please enter a new filename.", "ERROR!!!!!!", JOptionPane.ERROR_MESSAGE);
                   jTextField1.setText("");
                   flag=false;
            }
            else if(str.equals("success"))
                flag=true;
            
        }
              /*catch(Exception e)
              {
                  System.out.println(e);
                   JOptionPane.showMessageDialog(this, "Filename already present. Please enter a new filename.", "ERROR!!!!!!", JOptionPane.ERROR_MESSAGE);
                   jTextField1.setText("");
                   flag=false;
              }*/
              catch(Exception e)
              {
                  flag=false;
                   JOptionPane.showMessageDialog(this, "Please fill all entries correctly.", "ERROR!!!!!!", JOptionPane.ERROR_MESSAGE);
              }
            }
            if(flag)
            {
                jLabel3.setText("Hiding.....");
            jProgressBar1.setIndeterminate(true);            
            
            String strnew=jTextField1.getText();
            int index=name.lastIndexOf('\\');
            temp=name.substring(0, index);
            temp+="\\"+strnew+".png";
            System.out.println(temp);
            
            try {
            
            Encode en=new Encode(str1,name,temp);
            jProgressBar1.setIndeterminate(false);
            jLabel3.setText("Complete");
            jProgressBar1.setValue(100);
        } catch (Exception ex) {
            System.out.println(ex);
        }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Comparision obj = new Comparision(name,temp);
            this.setVisible(false);
            obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hiding("","").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
