
package package1;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Registration extends javax.swing.JFrame {
        
DefaultComboBoxModel obj=new DefaultComboBoxModel();

    public Registration() {
       
        initComponents();
         FillModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(457, 23, 151, 34);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(95, 97, 164, 30);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(95, 138, 164, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(95, 186, 164, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(95, 234, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Date Of Birth");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(95, 282, 164, 30);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Nationality");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(95, 330, 164, 30);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(680, 423, 87, 30);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Mobile No.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 380, 164, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(785, 423, 73, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(false);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(785, 459, 95, 30);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 430, 164, 30);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("e-mail ID");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 480, 164, 30);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton3.setText("Agree terms and conditions??");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(95, 538, 313, 37);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 21)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton4.setText("Decline");
        jRadioButton4.setOpaque(false);
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(95, 578, 97, 37);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Read");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(496, 538, 101, 33);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(785, 607, 104, 33);

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.setOpaque(false);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(297, 282, 60, 30);

        jComboBox2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        jComboBox2.setOpaque(false);
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(380, 280, 110, 30);

        jComboBox3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox3.setModel(obj
        );
        jComboBox3.setOpaque(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(510, 280, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(300, 100, 300, 30);

        jTextField2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(300, 140, 300, 30);

        jTextField3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(300, 430, 300, 30);

        jTextField4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(300, 380, 300, 30);

        jTextField5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(300, 330, 300, 30);

        jTextField6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(300, 480, 300, 30);

        jPasswordField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(300, 190, 300, 30);

        jPasswordField2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(0, 0, 102));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(300, 240, 300, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package1/Pictures/summer-days-ppt-backgrounds.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-50, 0, 1080, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
   

    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(jRadioButton3.isSelected() && error())
        {
            String s1=new String(jPasswordField1.getPassword());
            String s2=new String(jPasswordField2.getPassword());
            if(!(s1.contentEquals(s2)))
            {
                 JOptionPane.showMessageDialog(this, "Password mismatch", "ERROR!!!!!!", JOptionPane.INFORMATION_MESSAGE);
                 jPasswordField2.setText("");
            }
            else
            {
                try
                {
                    String c="";
                    if(jRadioButton1.isSelected())
                        c="male";
                    else if(jRadioButton2.isSelected())            
                        c="female";
            
                    Socket client;
                    BufferedReader in;
                    PrintWriter out;
                    client=new Socket("localhost",2013);
                    in=new BufferedReader(new InputStreamReader(client.getInputStream()));
                    out=new PrintWriter(client.getOutputStream(),true);
                    out.println("register");
                    out.println(jTextField1.getText());
                    out.println(jTextField2.getText());
                    out.println(new String(jPasswordField1.getPassword()));
                    out.println(jComboBox1.getSelectedItem().toString());
                    out.println(jComboBox2.getSelectedItem().toString());
                    out.println(jComboBox3.getSelectedItem().toString());
                    out.println(jTextField5.getText());
                    out.println(jTextField4.getText());
                    out.println(jTextField3.getText());
                    out.println(c);
                    out.println(jTextField6.getText());
                    String str12=in.readLine();
                    if(str12.equals("error"))
                        JOptionPane.showMessageDialog(this, "Please fill all entries correctly.", "WARNING!!!", JOptionPane.WARNING_MESSAGE);  
                    else if(str12.equals("complete"))
                    {
                        SelectTask obj=new SelectTask();
                        this.setVisible(false);
                        obj.setVisible(true);
                    }
                }              
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
        }
        else
        {
          if(!(jRadioButton3.isSelected()))
          JOptionPane.showMessageDialog(this, "Please accept the terms and conditions.", "WARNING!!!", JOptionPane.WARNING_MESSAGE);  
        }      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str="Thanks for using our software."
                +  "\n\nFollowing terms and conditions should be accepted :"
                +  "\n\n1. This software should not be used by a method other than the interface and instructions that we provide."
                +  "\n2. The details provided above in the form should be correct."
                +  "\n3. We will protect your privacy when you use our services. Your data will not be made public.";
                
        JOptionPane.showMessageDialog(this, str, "Terms and Conditions", JOptionPane.PLAIN_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
private void FillModel()
{
    int i;
for(i=1930;i<1996;i++)
{
   obj.addElement(i);
}
}

private boolean error()
{
  
    if((jTextField1.getText()==null)|(jTextField2.getText()==null)|(jTextField3.getText()==null)|(jTextField4.getText()==null)|(jTextField5.getText()==null)|(jTextField6.getText()==null)|(!(jRadioButton1.isSelected())&!(jRadioButton2.isSelected())))
    {
        JOptionPane.showMessageDialog(this, "Please fill all entries correctly.", "WARNING!!!", JOptionPane.WARNING_MESSAGE);  
        return false;      
    }
    else
        return true;
        }
}
